ajax/ajax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

ajax/app/urls.py
from django.urls import path 
from . import views 

urlpatterns = [
    path('appCreateView', views.appCreateView.as_view(), name='appCreateView'),
]

ajax/app/models.py
from distutils.command.upload import upload
from django.db import models

class Personne(models.Model):
    photo = models.ImageField(upload_to='images', null=True, blank=True)
    nom = models.CharField(max_length=100)
    numero = models.IntegerField()
    date_save = models.DateTimeField()
    
    class Meta:
        verbose_name=('Personne')
        verbose_name_plural=('Personnes')
        
    def __str__(self):
        return self.nom
    

ajax/app/views.py
from django.shortcuts import render
from . models import Personne 
from django.views.generic import CreateView
from django.contrib import messages
from .form import UserForm

class appCreateView(CreateView):
    model = Personne
    form_class = UserForm
    template_name = 'appCreateView.html'
    success_url = '/appCreateView'
  
       

ajax/app/templates/appCreateView.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<title>Document</title>
</head>
<body>
    <script></script>
    <form  enctype="multipart/form-data" id='post' method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type='submit' >send</button>
    </form>

    <script language='JavaScript'>
       
       $(document).on('submit', '#post', function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:"{% url 'appCreateView' %}",
            data:{
                photo:$('#id_photo').val(),
                nom:$('#id_nom').val(),
                numero:$('#id_numero').val(),
                date_save:$('#id_date_save').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),

            },
            success:function(){
                 alert("vos donnees ont ete enregistrer");
            },
           error:function(){
            alert('error !!');
           } 
        })
       })
    </script>
</body>
</html>